<a href="https://colab.research.google.com/github/mynameisyouji/MLstudy/blob/main/%EA%B8%B0%EA%B3%84%ED%95%99%EC%8A%B5%ED%8A%B9%EA%B0%95_%EC%88%99%EC%A0%9C__2(%EC%A0%9C%EC%B6%9C%EC%9A%A9).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [60]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score
from sklearn import metrics

In [54]:
from google.colab import drive
drive.mount('/gdrive', force_remount=True)
abalone_data=pd.read_csv('/gdrive/MyDrive/data/abalone.csv')
abalone_data.head(5)

Mounted at /gdrive


M  0.455  0.365  0.095   0.514  0.2245   0.101   0.15  15
0  M  0.350  0.265  0.090  0.2255  0.0995  0.0485  0.070   7
1  F  0.530  0.420  0.135  0.6770  0.2565  0.1415  0.210   9
2  M  0.440  0.365  0.125  0.5160  0.2155  0.1140  0.155  10
3  I  0.330  0.255  0.080  0.2050  0.0895  0.0395  0.055   7
4  I  0.425  0.300  0.095  0.3515  0.1410  0.0775  0.120   8

In [55]:
datax = np_abalone_data[:, 1:9]
datay = np_abalone_data[:, 0:1]
print(datax[0:5, :])
print(datay[0:10])

[[0.35 0.265 0.09 0.2255 0.0995 0.0485 0.07 7]
 [0.53 0.42 0.135 0.677 0.2565 0.1415 0.21 9]
 [0.44 0.365 0.125 0.516 0.2155 0.114 0.155 10]
 [0.33 0.255 0.08 0.205 0.0895 0.0395 0.055 7]
 [0.425 0.3 0.095 0.3515 0.141 0.0775 0.12 8]]
[['M']
 ['F']
 ['M']
 ['I']
 ['I']
 ['F']
 ['F']
 ['M']
 ['F']
 ['F']]


In [89]:
from sklearn.model_selection import train_test_split
trnx, tstx, trny, tsty = train_test_split(datax, datay, test_size=0.3, random_state=0)
print(trnx.shape, tstx.shape, trny.shape, tsty.shape)

(2923, 8) (1253, 8) (2923, 1) (1253, 1)


In [123]:
from sklearn import tree
tree_model = tree.DecisionTreeClassifier(max_depth=6, min_samples_split=7)
tree_model.fit(X=trnx, y=trny)
tree_pred = tree_model.predict(X=tstx)
tree_model.feature_importances_

array([0.05220877, 0.04147562, 0.01263029, 0.07341643, 0.04261857,
       0.56736954, 0.02171571, 0.18856507])

In [125]:
print(accuracy_score(tree_pred, tsty))

0.5562649640861931


In [126]:
# Ensemble
from sklearn.ensemble import RandomForestClassifier
rf_model = RandomForestClassifier(max_depth=15, n_estimators=100, random_state=0)
rf_model.fit(X=trnx, y=trny)
rf_pred = rf_model.predict(X=tstx)
print(metrics.accuracy_score(tsty, rf_pred))

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


0.5570630486831604


In [127]:
# Ensemble
from sklearn.ensemble import GradientBoostingClassifier
gbm_model = GradientBoostingClassifier(max_depth=3, n_estimators=30, random_state=0)
gbm_model.fit(X=trnx, y=trny)
gbm_pred = gbm_model.predict(X=tstx)
print(metrics.accuracy_score(tsty, gbm_pred))

/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.5658419792498005


In [132]:
from sklearn.neural_network import MLPClassifier

clf = MLPClassifier(hidden_layer_sizes=(10,), max_iter=500)
clf.fit(trnx, trny)
tsty_hat = clf.predict(tstx)
print(accuracy_score(tsty, tsty_hat))

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:1109: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.5554668794892259


In [133]:
clf2 = MLPClassifier(hidden_layer_sizes=(32,16,8), max_iter=500)
clf2.fit(trnx, trny)
tsty_hat2 = clf2.predict(tstx)

print(accuracy_score(tsty, tsty_hat2))

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:1109: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.5674381484437351
